name: deploy to aliyun oss

on:
  push:
    branches:
      - master

jobs:
  linux-20_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: setup oss env
      run: |
        curl -o ~/bin/ossuitl -L http://gosspublic.alicdn.com/ossutil/1.6.10/ossutil64
        chmod a+rx ~/bin/ossuitl
        ossutil config -e oss-cn-hongkong.aliyuncs.com -i ${{ secrets.OSS_KEY_ID }} -k ${{ secrets.OSS_KEY_SECRET }}

    - name: cp files to oss
      run: ossutil cp -r ./ oss://github-ci/
