name: deploy to aliyun oss

on:
  push:
    branches:
      - master

jobs:
  linux-20_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: copy fiels to oss
      run: |
        mkdir -p ~/bin
        curl -o ~/bin/ossuitl -L http://gosspublic.alicdn.com/ossutil/1.6.10/ossutil64
        chmod a+rx ~/bin/ossuitl
        ~/bin/ossutil config -e oss-cn-hongkong.aliyuncs.com -i ${{ secrets.OSS_KEY_ID }} -k ${{ secrets.OSS_KEY_SECRET }}
        ~/bin/ossutil cp -r ./ oss://github-ci/
