name: deploy to aliyun oss

on:
  push:
    branches:
      - master

jobs:
  linux-20_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: copy files to oss
      run: |
        mkdir -p ~/bin
        aliOSS="~/bin/ossutil"
        curl -o $aliOSS-L http://gosspublic.alicdn.com/ossutil/1.6.10/ossutil64
        chmod a+rx $aliOSS
        $aliOSS config -e oss-cn-hongkong.aliyuncs.com -i ${{ secrets.OSS_KEY_ID }} -k ${{ secrets.OSS_KEY_SECRET }}
        $aliOSS cp -r ./ oss://github-ci/
